/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {


  // AI & Machine Learning sidebar
  aiSidebar: [
    {
      type: 'category',
      label: 'AI & Machine Learning',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai',
        },
      ],
    },
  ],

  // Frontend Development sidebar
  frontendSidebar: [
    {
      type: 'category',
      label: 'Frontend',
      items: [
        {
          type: 'autogenerated',
          dirName: 'frontend',
        },
      ],
    },
  ],

  // DevOps sidebar
  devopsSidebar: [
    {
      type: 'category',
      label: 'DevOps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'devops',
        },
      ],
    },
  ],

  // Software Engineering sidebar
  softwareEngineeringSidebar: [
    {
      type: 'category',
      label: 'Software Engineering',
      items: [
        {
          type: 'autogenerated',
          dirName: 'software-engineering',
        },
      ],
    },
  ],
};

module.exports = sidebars;
